name: address_linker
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  args: ^2.5.0
  collection: ^1.18.0
  dio: ^5.8.0+1
  freezed_annotation: ^3.0.0
  hive: ^2.2.3
  json_annotation: ^4.9.0
  yx_scope: ^1.0.2

dev_dependencies:
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  lints: ^6.0.0
  test: ^1.24.0
  very_good_analysis: ^8.0.0
